version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  website:
    build: .
    # Dando nome aos bois
    image: bootcamp-chatbot
    depends_on:
      - 'postgres'
    # Comando default quando levantar o container
    command: rackup config.ru -o 0.0.0.0
    ports:
      - '9292:9292'
    volumes:
      - bundle_cache:/bundle
      - '.:/chatbot'

volumes:
  postgres:
  bundle_cache: